apiVersion: v1
kind: ad-hoc
metadata:
  storage_api_version: storage.k8s.io/v1
  provisioner_name: nfs.csi.k8s.io
  path_name: csi-driver-nfs
  driver_name: csi-driver-nfs
  repository_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
